/*Script to bring all the views from scattered tables, like oi_PostViews, oi_SpecialPageViews, etc. into oi_PhysicalPageViews*/

INSERT INTO [dbo].[oi_PhysicalPages] (Id, DateCreated, [Path])
SELECT NEWID(), GETDATE(), '/pages/' + NanoId + '/' FROM [dbo].[oi_Pages];

INSERT INTO [dbo].[oi_PhysicalPages] (Id, DateCreated, [Path])
SELECT NEWID(), GETDATE(), '/posts/' + NanoId + '/' FROM [dbo].[oi_Posts];

INSERT INTO [dbo].[oi_PhysicalPages] (Id, DateCreated, [Path])
SELECT NEWID(), GETDATE(), '/specialpages/' + NanoId + '/' FROM [dbo].[oi_SpecialPages];

INSERT INTO [dbo].[oi_PhysicalPages] (Id, DateCreated, [Path])
SELECT NEWID(), GETDATE(), '/videos/' + NanoId + '/' FROM [dbo].[oi_Videos];

INSERT INTO [dbo].[oi_PhysicalPageViews] (
	[Id],
	[PhysicalPageId],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	[Admin],
	[UserId],
	[Content_Id],
	[Content_Type])
SELECT
	NEWID(),
	pp.[Id],
	v.[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	0,
	NULL,
	p.Id,
	'OrigamiPage'
FROM [dbo].[oi_PageViews] v
JOIN [dbo].[oi_Pages] p on v.PageId = p.Id
JOIN [dbo].[oi_PhysicalPages] pp ON pp.[Path] = '/pages/' + p.NanoId + '/';


INSERT INTO [dbo].[oi_PhysicalPageViews] (
	[Id],
	[PhysicalPageId],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	[Admin],
	[UserId],
	[Content_Id],
	[Content_Type])
SELECT
	NEWID(),
	pp.[Id],
	v.[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	0,
	NULL,
	p.Id,
	'OrigamiPost'
FROM [dbo].[oi_PostViews] v
JOIN [dbo].[oi_Posts] p on v.PostId = p.Id
JOIN [dbo].[oi_PhysicalPages] pp ON pp.[Path] = '/posts/' + p.NanoId + '/';


INSERT INTO [dbo].[oi_PhysicalPageViews] (
	[Id],
	[PhysicalPageId],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	[Admin],
	[UserId],
	[Content_Id],
	[Content_Type])
SELECT
	NEWID(),
	pp.[Id],
	v.[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	0,
	NULL,
	p.Id,
	'OrigamiSpecialPage'
FROM [dbo].[oi_SpecialPageViews] v
JOIN [dbo].[oi_SpecialPages] p on v.SpecialPageId = p.Id
JOIN [dbo].[oi_PhysicalPages] pp ON pp.[Path] = '/specialpages/' + p.NanoId + '/';


INSERT INTO [dbo].[oi_PhysicalPageViews] (
	[Id],
	[PhysicalPageId],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	[Admin],
	[UserId],
	[Content_Id],
	[Content_Type])
SELECT
	NEWID(),
	pp.[Id],
	v.[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot],
	0,
	NULL,
	p.Id,
	'OrigamiVideo'
FROM [dbo].[oi_VideoViews] v
JOIN [dbo].[oi_Videos] p on v.VideoId = p.Id
JOIN [dbo].[oi_PhysicalPages] pp ON pp.[Path] = '/videos/' + p.NanoId + '/';