/*Script to copy all information from pages, posts, special-pages, videos into the master table oi_Contents*/

INSERT INTO [dbo].[oi_Contents] (
	[Id], 
	[Type], 
	[SubType], 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	[NanoId],
	[IsDraft],
	[StartDate],
	[EndDate])
SELECT
	[Id], 
	'OrigamiPage', 
	NULL, 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	0[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	NULL[DateReleased],
	SUBSTRING(CONVERT(VARCHAR(36), NEWID()), 1, 8)[NanoId],
	0[IsDraft],
	NULL[StartDate],
	NULL[EndDate]
FROM [nbolt_blogengine_2a].dbo.be_Pages;


INSERT INTO [dbo].[oi_Contents] (
	[Id], 
	[Type], 
	[SubType], 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	[NanoId],
	[IsDraft],
	[StartDate],
	[EndDate])
SELECT
	[Id], 
	'OrigamiPost'[Type], 
	NULL[SubType], 
	[BlogId], 
	NULL[ParentId], 
	NULL[Keywords], 
	0[IsFrontPage], 
	NULL[MediaFile_LocalPath], 
	NULL[MediaFile_DateCreated], 
	NULL[MediaFile_DateModified], 
	NULL[MediaFile_Language], 
	NULL[MediaFile_WebPath], 
	NULL[Subtitle1_LocalPath], 
	NULL[Subtitle1_DateCreated], 
	NULL[Subtitle1_DateModified], 
	NULL[Subtitle1_Language], 
	NULL[Subtitle2_LocalPath], 
	NULL[Subtitle1_WebPath], 
	NULL[Subtitle2_DateCreated], 
	NULL[Subtitle2_DateModified], 
	NULL[Subtitle2_Language], 
	NULL[Subtitle2_WebPath], 
	NULL[Subtitle3_LocalPath], 
	NULL[Subtitle3_DateCreated], 
	NULL[Subtitle3_DateModified], 
	NULL[Subtitle3_Language], 
	NULL[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	NULL[DateReleased],
	SUBSTRING(CONVERT(VARCHAR(36), NEWID()), 1, 8)[NanoId],
	0[IsDraft],
	NULL[StartDate],
	NULL[EndDate]
FROM [nbolt_blogengine_2a].dbo.be_Posts;



INSERT INTO [dbo].[oi_Contents] (
	[Id], 
	[Type], 
	[SubType], 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	[NanoId],
	[IsDraft],
	[StartDate],
	[EndDate])
SELECT
	[Id], 
	'OrigamiSpecialMessage'[Type], 
	[Type], 
	NULL[BlogId], 
	NULL[ParentId], 
	NULL[Keywords], 
	0[IsFrontPage], 
	NULL[MediaFile_LocalPath], 
	NULL[MediaFile_DateCreated], 
	NULL[MediaFile_DateModified], 
	NULL[MediaFile_Language], 
	NULL[MediaFile_WebPath], 
	NULL[Subtitle1_LocalPath], 
	NULL[Subtitle1_DateCreated], 
	NULL[Subtitle1_DateModified], 
	NULL[Subtitle1_Language], 
	NULL[Subtitle2_LocalPath], 
	NULL[Subtitle1_WebPath], 
	NULL[Subtitle2_DateCreated], 
	NULL[Subtitle2_DateModified], 
	NULL[Subtitle2_Language], 
	NULL[Subtitle2_WebPath], 
	NULL[Subtitle3_LocalPath], 
	NULL[Subtitle3_DateCreated], 
	NULL[Subtitle3_DateModified], 
	NULL[Subtitle3_Language], 
	NULL[Subtitle3_WebPath], 
	[Title], 
	NULL[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	0[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	''[Slug],
	[IsDeleted],
	[AuthorId],
	NULL[DateReleased],
	[NanoId],
	[IsDraft],
	NULL[StartDate],
	NULL[EndDate]
FROM [nbolt_blogengine_2a].dbo.be_SpecialMessages



INSERT INTO [dbo].[oi_Contents] (
	[Id], 
	[Type], 
	[SubType], 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	[NanoId],
	[IsDraft],
	[StartDate],
	[EndDate])
SELECT
	[Id], 
	'OrigamiSpecialPage'[Type], 
	[Type], 
	NULL[BlogId], 
	NULL[ParentId], 
	NULL[Keywords], 
	0[IsFrontPage], 
	NULL[MediaFile_LocalPath], 
	NULL[MediaFile_DateCreated], 
	NULL[MediaFile_DateModified], 
	NULL[MediaFile_Language], 
	NULL[MediaFile_WebPath], 
	NULL[Subtitle1_LocalPath], 
	NULL[Subtitle1_DateCreated], 
	NULL[Subtitle1_DateModified], 
	NULL[Subtitle1_Language], 
	NULL[Subtitle2_LocalPath], 
	NULL[Subtitle1_WebPath], 
	NULL[Subtitle2_DateCreated], 
	NULL[Subtitle2_DateModified], 
	NULL[Subtitle2_Language], 
	NULL[Subtitle2_WebPath], 
	NULL[Subtitle3_LocalPath], 
	NULL[Subtitle3_DateCreated], 
	NULL[Subtitle3_DateModified], 
	NULL[Subtitle3_Language], 
	NULL[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	0[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	NULL[DateReleased],
	[NanoId],
	[IsDraft],
	NULL[StartDate],
	NULL[EndDate]
FROM [nbolt_blogengine_2a].dbo.be_SpecialPages;



INSERT INTO [dbo].[oi_Contents] (
	[Id], 
	[Type], 
	[SubType], 
	[BlogId], 
	[ParentId], 
	[Keywords], 
	[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	[NanoId],
	[IsDraft],
	[StartDate],
	[EndDate])
SELECT
	[Id], 
	'OrigamiVideo'[Type], 
	NULL[SubType], 
	[BlogId], 
	NULL[ParentId], 
	NULL[Keywords], 
	0[IsFrontPage], 
	[MediaFile_LocalPath], 
	[MediaFile_DateCreated], 
	[MediaFile_DateModified], 
	[MediaFile_Language], 
	[MediaFile_WebPath], 
	[Subtitle1_LocalPath], 
	[Subtitle1_DateCreated], 
	[Subtitle1_DateModified], 
	[Subtitle1_Language], 
	[Subtitle2_LocalPath], 
	[Subtitle1_WebPath], 
	[Subtitle2_DateCreated], 
	[Subtitle2_DateModified], 
	[Subtitle2_Language], 
	[Subtitle2_WebPath], 
	[Subtitle3_LocalPath], 
	[Subtitle3_DateCreated], 
	[Subtitle3_DateModified], 
	[Subtitle3_Language], 
	[Subtitle3_WebPath], 
	[Title], 
	[Description], 
	[Content], 
	[DateCreated], 
	[DateModified], 
	[IsPublished], 
	[IsCommentEnabled],
	[DatePublished],
	[AdditionalInfo],
	[Slug],
	[IsDeleted],
	[AuthorId],
	[DateReleased],
	SUBSTRING(CONVERT(VARCHAR(36), NEWID()), 1, 8)[NanoId],
	0[IsDraft],
	NULL[StartDate],
	NULL[EndDate]
FROM [nbolt_blogengine_2a].dbo.be_Videos;












INSERT INTO [nbolt_blogengine_2b].dbo.oi_ContentRatings (
	[Id],
	[ContentId],
	[Rating],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot])
SELECT 
	[Id],
	[PostId],
	[Rating],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	0[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot]
FROM [nbolt_blogengine_2a].dbo.be_PostRatings;





INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentRatings (
	[Id],
	[ContentId],
	[Rating],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot])
SELECT 
	[Id],
	[VideoId],
	[Rating],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot]
FROM [nbolt_blogengine_2a].dbo.be_VideoRatings;





INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentComments (
	[Id],
	[ContentId],
	[ParentId],
	[Content],
	[DateCreated],
	[DateModified],
	[SocialProfileId],
	[PinnedById],
	[Ip],
	[IsDeleted],
	[IsApproved],
	[IsSpam],
	[AdditionalInfo],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[ModeratedById])
SELECT
	[Id],
	[PostId],
	[ParentId],
	[Content],
	[DateCreated],
	[DateModified],
	[SocialProfileId],
	[PinnedById],
	[Ip],
	[IsDeleted],
	[IsApproved],
	[IsSpam],
	[AdditionalInfo],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[ModeratedById]
FROM [nbolt_blogengine_2a].dbo.be_PostComments;







INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentComments (
	[Id],
	[ContentId],
	[ParentId],
	[Content],
	[DateCreated],
	[DateModified],
	[SocialProfileId],
	[PinnedById],
	[Ip],
	[IsDeleted],
	[IsApproved],
	[IsSpam],
	[AdditionalInfo],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[ModeratedById],
	
	[Browser], [HostAddress], [HostName], [IsBot], [IsMobileDevice], [Platform], [UserAgent]

	)
SELECT
	[Id],
	[VideoId],
	[ParentId],
	[Content],
	[DateCreated],
	[DateModified],
	[SocialProfileId],
	[PinnedById],
	[Ip],
	[IsDeleted],
	[IsApproved],
	[IsSpam],
	[AdditionalInfo],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[ModeratedById],
	''[Browser], ''[HostAddress], ''[HostName], 0[IsBot], 0[IsMobileDevice], ''[Platform], ''[UserAgent]
FROM [nbolt_blogengine_2a].dbo.be_VideoComments;







INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentCategories (
	[Id],
	[CategoryId],
	[ContentId])
SELECT
	[Id],
	[CategoryId],
	[PostId]
FROM [nbolt_blogengine_2a].dbo.be_PostCategories;



INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentCategories (
	[Id],
	[CategoryId],
	[ContentId])
SELECT
	[Id],
	[CategoryId],
	[VideoId]
FROM [nbolt_blogengine_2a].dbo.be_VideoCategories;






INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentCommentReactions (
	[Id],
	[CommentId],
	[Reaction],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot])
SELECT 
	[Id],
	[CommentId],
	[Reaction],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot]
FROM [nbolt_blogengine_2a].dbo.be_PostCommentReactions;






INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentCommentReactions (
	[Id],
	[CommentId],
	[Reaction],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot])
SELECT 
	[Id],
	[CommentId],
	[Reaction],
	[DateCreated],
	[HostAddress],
	[HostName],
	[UserAgent],
	[Platform],
	[Browser],
	[IsMobileDevice],
	[UrlReferrer],
	[Url],
	[Location_City],
	[Location_Country],
	[Location_CountryCode],
	[Location_Latitude],
	[Location_Longitude],
	[Location_Region],
	[Location_RegionCode],
	[Location_TimeZone],
	[Location_TimeZoneOffset],
	[Location_ZipCode],
	[SocialProfileId],
	[IsBot]
FROM [nbolt_blogengine_2a].dbo.be_VideoCommentReactions;





INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentTags (Id, ContentId, Tag)
SELECT Id, PostId, Tag FROM [nbolt_blogengine_2a].dbo.be_PostTags;


INSERT INTO [nbolt_blogengine_2a].dbo.be_ContentTags (Id, ContentId, Tag)
SELECT Id, VideoId, Tag FROM [nbolt_blogengine_2a].dbo.be_VideoTags;