<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Origami.LocalizationAnalyzer'">
    <ProjectReference Include="..\Origami.LocalizationAnalyzer\Origami.LocalizationAnalyzer.csproj" 
                      OutputItemType="Analyzer"
					  ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>