<Project>
  <!--<ItemGroup Condition="'$(MSBuildProjectName)' != 'Origami.LocalizationAnalyzer'">
    <ProjectReference Include="..\Origami.LocalizationAnalyzer\Origami.LocalizationAnalyzer.csproj" 
                      OutputItemType="Analyzer"
					  ReferenceOutputAssembly="false" />
  </ItemGroup>-->
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Origami.LocalizationGenerator'">
    <ProjectReference Include="..\Origami.LocalizationGenerator\Origami.LocalizationGenerator.csproj" 
                      OutputItemType="Analyzer"
					  ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>